DROP DATABASE IF EXISTS AutoAssicurazioni;

CREATE DATABASE AutoAssicurazioni;

USE AutoAssicurazioni;

CREATE TABLE Proprietari(
	CodFiscale CHARACTER(16) NOT NULL,
	Cognome VARCHAR(30) NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	DataNascita DATE NOT NULL,
	PRIMARY KEY(CodFiscale));
	
CREATE TABLE Assicurazioni(
	CodAss INT NOT NULL AUTO_INCREMENT,
	Nome VARCHAR(30) NOT NULL,
	Sede VARCHAR(100) NOT NULL,
	PRIMARY KEY(CodAss));
	
CREATE TABLE Automobili(
	Targa VARCHAR(10) NOT NULL,
	Marca VARCHAR(20) NOT NULL,
	Cilindrata INT NOT NULL,
	Potenza INT NOT NULL,
	CodFiscale CHARACTER(16),
	CodAss INT NULL,
	PRIMARY KEY(Targa),
	FOREIGN KEY(CodFiscale) REFERENCES Proprietari(CodFiscale) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY(CodAss) REFERENCES Assicurazioni(CodAss) ON DELETE RESTRICT ON UPDATE CASCADE);
	
CREATE TABLE Sinistri(
	CodS INT NOT NULL AUTO_INCREMENT,
	Localita VARCHAR(100) NOT NULL,
	Data DATE NOT NULL,
	PRIMARY KEY(CodS));

CREATE TABLE AutoCoinvolte(
	CodS INT NOT NULL,
	Targa VARCHAR(10) NOT NULL,
	ImportoDanno DECIMAL(7,2) NOT NULL,
	PRIMARY KEY(CodS, Targa),
	FOREIGN KEY(CodS) REFERENCES Sinistri(CodS) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(Targa) REFERENCES Automobili(Targa) ON DELETE CASCADE ON UPDATE CASCADE);


LOAD DATA
INFILE '%currentPathMySql%/Proprietari.csv'
INTO TABLE Proprietari
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA
INFILE '%currentPathMySql%/Assicurazioni.csv'
INTO TABLE Assicurazioni
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA
INFILE '%currentPathMySql%/Automobili.csv'
INTO TABLE Automobili
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA
INFILE '%currentPathMySql%/Sinistri.csv'
INTO TABLE Sinistri
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

LOAD DATA
INFILE '%currentPathMySql%/AutoCoinvolte.csv'
INTO TABLE AutoCoinvolte
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;